name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate with Google
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC_JSON" > ~/.clasprc.json

      - name: Push code to Google Apps Script
        run: clasp push -f
